name: Build and release Docker image BLK

on:
  workflow_dispatch:
  push:
    branches:
      - feature/blk-doge
    paths:
      - 'src/**/*'
      - 'packages/**/*'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}

    - name: Build and release Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        no-cache: true
        tags: |
          ${{ secrets.CI_REGISTRY }}/${{ secrets.CI_REGISTRY_REPO }}/${{ vars.SERVICE_NAME_1 }}:${{ github.sha }}
          ${{ secrets.CI_REGISTRY }}/${{ secrets.CI_REGISTRY_REPO }}/${{ vars.SERVICE_NAME_1 }}:latest

    - name: Trigger Deploy Workflow
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GIT_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        event-type: Deploy-BLK
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
