name: Deploy service RPC for Bells Testnet

on:
  workflow_dispatch:
  repository_dispatch:
    types: [Deploy-RPC-Bells]

jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.ref }}

    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.CI_REGISTRY }}
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_PASSWORD }}

    - name: Check if Image Exists
      env:
        CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
        CI_REGISTRY_REPO: ${{ secrets.CI_REGISTRY_REPO }}
        SERVICE_NAME: ${{ vars.SERVICE_NAME_2 }}
        COIN: bells
        SERVICE_TAG: ${{ github.event.client_payload.sha }}
      run: |
        if docker manifest inspect ${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}-${COIN}:${SERVICE_TAG} > /dev/null; then
          echo "Image exists"
        else
          echo "Image does not exist"
          exit 1
        fi

    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      env:
        CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
        CI_REGISTRY_REPO: ${{ secrets.CI_REGISTRY_REPO }}
        SERVICE_NAME: ${{ vars.SERVICE_NAME_2 }}
        SERVICE_TAG: ${{ github.event.client_payload.sha }}
        DOCKER_COMPOSE_FILE: ${{ vars.DOCKER_COMPOSE_FILE_2 }}
        COIN: bells
        NETWORK: testnet
      with:
        host: ${{ secrets.BELLS_TESTNET_HOST_1 }}
        username: ${{ secrets.BELLS_TESTNET_HOST_1_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: CI_REGISTRY,CI_REGISTRY_REPO,SERVICE_NAME,SERVICE_TAG,DOCKER_COMPOSE_FILE,COIN,NETWORK
        script: |
          cd /opt/${COIN}-${NETWORK}/services/${SERVICE_NAME}
          sed -i "s|image: ${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}-${COIN}:.*|image: ${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}-${COIN}:${SERVICE_TAG}|" ${DOCKER_COMPOSE_FILE}
          cd ../../
          docker compose up -d --force-recreate ${COIN}-${NETWORK}-${SERVICE_NAME}