name: Deploy service for Doge Mainnet

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Deploy
      uses: appleboy/ssh-action@v1.0.0
      env:
        CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
        CI_REGISTRY_REPO: ${{ secrets.CI_REGISTRY_REPO }}
        SERVICE_NAME: ${{ vars.SERVICE_NAME }}
        SERVICE_TAG: ${{ github.sha }}
        DOCKER_COMPOSE_FILE: ${{ vars.DOCKER_COMPOSE_FILE }}
        COIN: doge
        NETWORK: mainnet
      with:
        host: ${{ secrets.DOGE_MAINNET_HOST_1 }}
        username: ${{ secrets.DOGE_MAINNET_HOST_1_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: CI_REGISTRY,CI_REGISTRY_REPO,SERVICE_NAME,SERVICE_TAG,DOCKER_COMPOSE_FILE,COIN,NETWORK
        script: |
          cd /opt/${COIN}-${NETWORK}/services/${SERVICE_NAME}
          sed -i "s|image: ${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}:.*|image: ${CI_REGISTRY}/${CI_REGISTRY_REPO}/${SERVICE_NAME}:${SERVICE_TAG}|" ${DOCKER_COMPOSE_FILE}
          cd ../../
          docker compose up -d --force-recreate ${COIN}-${NETWORK}-${SERVICE_NAME}