name: Wipe RPC service for Bells Mainnet

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Wipe
      uses: appleboy/ssh-action@v1.0.0
      env:
        SERVICE_NAME: ${{ vars.SERVICE_NAME_2 }}
        SERVICE_DIR_1: ${{ vars.SERVICE_DIR_1 }}
        SERVICE_DIR_2: ${{ vars.SERVICE_DIR_2 }}
        COIN: bells
        NETWORK: mainnet
      with:
        host: ${{ secrets.BELLS_MAINNET_HOST_1 }}
        username: ${{ secrets.BELLS_MAINNET_HOST_1_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: SERVICE_NAME,COIN,NETWORK,SERVICE_DIR_1,SERVICE_DIR_2
        script: |
          cd /opt/${COIN}-${NETWORK}
          docker rm -f ${COIN}-${NETWORK}-${SERVICE_NAME}
          cd /opt/${COIN}-${NETWORK}/services/${SERVICE_NAME}
          rm -rf ${SERVICE_DIR_1}/* ${SERVICE_DIR_2}/*
